-- Student Number: 22603770
-- Name: Lucas Zhan
-- Class: LCD
-- Date: 2026-09-16

SELECT DB_NAME() AS current_database;

SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HR';

SELECT TOP 1 *
FROM HR.EMPLOYEES
WHERE LAST_NAME = 'SMITH';

SELECT TOP 1 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME
FROM HR.EMPLOYEES
WHERE FIRST_NAME = 'Lucas';

SELECT 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE SALARY > '10000' AND DEPARTMENT_ID <> '80';

SELECT 
    FIRST_NAME,
    LAST_NAME
FROM HR.EMPLOYEES
WHERE MANAGER_ID is NULL;

SELECT
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    MANAGER_ID,
    LOCATION_ID
FROM HR.DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT';

SELECT *
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = '60';

SELECT *
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = '770';

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'EMPLOYEES';

SELECT COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'EMPLOYEES' AND IS_NULLABLE = 'NO';

INSERT INTO HR.EMPLOYEES
    (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE,
    JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES
    (770, 'Lucas', 'Zhan', 'LZHAN','987.654.1123', GETDATE(), 'IT_PROG', 10000, NULL, NULL, 60);

SELECT 
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE,
    JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 770;

DELETE FROM HR.EMPLOYEES WHERE EMPLOYEE_ID = 770;
